global:
  resolve_timeout: 5m

route:
  group_by: ["alertname", "severity"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "webhook-placeholder"
  routes:
    - match:
        severity: critical
      receiver: "webhook-placeholder"
      repeat_interval: 15m

receivers:
  - name: "webhook-placeholder"
    webhook_configs:
      - url: "http://localhost:9095/webhook"
        send_resolved: true
        # Para integrar Slack:
        # slack_configs:
        #   - api_url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
        #     channel: "#alerts"
        #     send_resolved: true
        #     title: '{{ .CommonAnnotations.summary }}'
        #     text: '{{ .CommonAnnotations.description }}'
        # Para integrar Email:
        # email_configs:
        #   - to: 'alerts@famachat.com.br'
        #     from: 'alertmanager@famachat.com.br'
        #     smarthost: 'smtp.gmail.com:587'
        #     auth_username: 'alertmanager@famachat.com.br'
        #     auth_password: '{{ .SecretEnv "SMTP_PASSWORD" }}'

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname"]
